# test.all.sh ... run test suite from test suite directory 
# autogenerated Thu Jul 20 17:01:07 MDT 2017 by jax using command:
# gensh -to test.all.sh -path /opt/ublu/ublu.jar -optr d DEFAULTS @defaults ${ full path to defaults file }$ -optr w WORKDIR @wdir ${ Work directory for test }$ -optr o OUTFILE @ofile ${ Output file }$ ${ test.all.sh ... run test suite from test suite directory }$ ./test.all.ublu ${ test.all ( @defaults @wdir @ofile ) }$

# Usage message
function usage {
echo "test.all.sh ... run test suite from test suite directory "
echo "This shell script was autogenerated Thu Jul 20 17:01:07 MDT 2017 by jax."
echo "Usage: $0 [silent] -h -d DEFAULTS -w WORKDIR -o OUTFILE "
echo "	where"
echo "	-h		display this help message and exit 0"
echo "	-D some.property="some value"	pass a property to the JVM (can be used many times)"
echo "	-X xOpt		pass a -X option to the JVM (can be used many times)"
echo "	-d DEFAULTS	full path to defaults file  (required option)"
echo "	-w WORKDIR	Work directory for test  (required option)"
echo "	-o OUTFILE	Output file  (required option)"
echo "---"
echo "If the keyword 'silent' appears ahead of all options, then included files will not echo and prompting is suppressed."
echo "Exit code is the result of execution, or 0 for -h or 2 if there is an error in processing options"
}

#Test if user wants silent includes
if [ "$1" == "silent" ]
then
	SILENT="-silent "
	shift
else
	SILENT=""
fi

# Process options
while getopts d:w:o:D:X:h the_opt
do
	case "$the_opt" in
		d)	DEFAULTS="$OPTARG";;
		w)	WORKDIR="$OPTARG";;
		o)	OUTFILE="$OPTARG";;
		D)	JVMPROPS="${JVMPROPS} -D${OPTARG}";;
		X)	JVMOPTS="${JVMOPTS} -X${OPTARG}";;
		[?])	usage;exit 2;;

	esac
done
shift `expr ${OPTIND} - 1`
if [ $# -ne 0 ]
then
	echo "Superfluous argument(s) $*"
	usage
	exit 2
fi

# Translate options to tuple assignments
if [ "${DEFAULTS}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @defaults -trim \${ ${DEFAULTS} }$ "
else
	echo "Option -d DEFAULTS is a required option but is not present."
	usage
	exit 2
fi
if [ "${WORKDIR}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @wdir -trim \${ ${WORKDIR} }$ "
else
	echo "Option -w WORKDIR is a required option but is not present."
	usage
	exit 2
fi
if [ "${OUTFILE}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @ofile -trim \${ ${OUTFILE} }$ "
else
	echo "Option -o OUTFILE is a required option but is not present."
	usage
	exit 2
fi

SCRIPTDIR=$(CDPATH= cd "$(dirname "$0")" && pwd)

# Invocation
java${JVMOPTS}${JVMPROPS} -Dublu.includepath="" -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}./test.all.ublu test.all \( @defaults @wdir @ofile \) 
exit $?
