# audJournal.sh ... read entries from audit journal 
# autogenerated Mon Mar 02 15:38:16 MST 2015 by jwoehr using command:
# gensh -to audJournal.sh -path /opt/ublu/ublu.jar -optr s SERVER @server ${ Server }$ -optr u USER @user ${ User }$ -optr p PASSWORD @password ${ Password }$ -optr n NUMENTRIES @numentries ${ number of journal entries to read }$ -optr f FILENAME @filename ${ filename to write journal to }$ ${ audJournal.sh ... read entries from audit journal }$ /opt/api-java/examples/audJournal.ublu ${ audJournal ( @server @user @password @numentries @filename ) }$

# Usage message
function usage () { 
echo "Usage: $0 [silent] -h -s SERVER -u USER -p PASSWORD -n NUMENTRIES -f FILENAME "
echo "	where"
echo "	-h		display this help message and exit 0"
echo "	-s SERVER	Server  (required option)"
echo "	-u USER	User  (required option)"
echo "	-p PASSWORD	Password  (required option)"
echo "	-n NUMENTRIES	number of journal entries to read  (required option)"
echo "	-f FILENAME	filename to write journal to  (required option)"
echo "---"
echo "If the keyword 'silent' appears ahead of all options, then included files will not echo and prompting is suppressed."
echo "Exit code is the result of execution, or 0 for -h or 2 if there is an error in processing options"
}

#Test if user wants silent includes
if [ "$1" == "silent" ]
then
	SILENT="-silent "
	shift
else
	SILENT=""
fi

# Process options
options=`getopt s:u:p:n:f:h  $*`
if [ $? != 0 ]
then
	usage
	exit 2
fi
for i in  $options  {
do
	case "$i"
	in
		-s)
			SERVER="$2";shift;
			shift;;

		-u)
			USER="$2";shift;
			shift;;

		-p)
			PASSWORD="$2";shift;
			shift;;

		-n)
			NUMENTRIES="$2";shift;
			shift;;

		-f)
			FILENAME="$2";shift;
			shift;;

		-h)
			usage;exit 0;shift;
			shift;;

		--)
			shift; break;;
	esac
done

# Translate options to tuple assignments
if [ "${SERVER}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @server -trim \${ ${SERVER} }$ "
else
	echo "Option -s SERVER is a required option but is not present."
	usage
	exit 2
fi
if [ "${USER}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @user -trim \${ ${USER} }$ "
else
	echo "Option -u USER is a required option but is not present."
	usage
	exit 2
fi
if [ "${PASSWORD}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @password -trim \${ ${PASSWORD} }$ "
else
	echo "Option -p PASSWORD is a required option but is not present."
	usage
	exit 2
fi
if [ "${NUMENTRIES}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @numentries -trim \${ ${NUMENTRIES} }$ "
else
	echo "Option -n NUMENTRIES is a required option but is not present."
	usage
	exit 2
fi
if [ "${FILENAME}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @filename -trim \${ ${FILENAME} }$ "
else
	echo "Option -f FILENAME is a required option but is not present."
	usage
	exit 2
fi

# Invocation
java -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}/opt/api-java/examples/audJournal.ublu audJournal \( @server @user @password @numentries @filename \) 
exit $?
