# listobjs.sh ... list all objects matching a specification 
# autogenerated Thu Mar 12 11:49:22 MDT 2015 by jwoehr using command:
# gensh -to listobjs.sh -path /opt/ublu/ublu.jar -optr s SERVER @server ${ Server to connect to }$ -optr u USER @user ${ User }$ -optr p PASSWORD @password ${ Password }$ -optr l LIBRARY @library ${ Library spec }$ -optr n OBJNAME @objname ${ Object name spec }$ -optr t OBJTYPE @objtype ${ Object type spec }$ ${ listobjs.sh ... list all objects matching a specification }$ /opt/api-java/examples/listobjs.ublu ${ listObjs ( @server @user @password @library @objname @objtype ) }$

# Usage message
function usage () { 
echo "Usage: $0 [silent] -h -s SERVER -u USER -p PASSWORD -l LIBRARY -n OBJNAME -t OBJTYPE "
echo "	where"
echo "	-h		display this help message and exit 0"
echo "	-s SERVER	Server to connect to  (required option)"
echo "	-u USER	User  (required option)"
echo "	-p PASSWORD	Password  (required option)"
echo "	-l LIBRARY	Library spec  (required option)"
echo "	-n OBJNAME	Object name spec  (required option)"
echo "	-t OBJTYPE	Object type spec  (required option)"
echo "---"
echo "If the keyword 'silent' appears ahead of all options, then included files will not echo and prompting is suppressed."
echo "Exit code is the result of execution, or 0 for -h or 2 if there is an error in processing options"
}

#Test if user wants silent includes
if [ "$1" == "silent" ]
then
	SILENT="-silent "
	shift
else
	SILENT=""
fi

# Process options
options=`getopt s:u:p:l:n:t:h  $*`
if [ $? != 0 ]
then
	usage
	exit 2
fi
for i in  $options  {
do
	case "$i"
	in
		-s)
			SERVER="$2";shift;
			shift;;

		-u)
			USER="$2";shift;
			shift;;

		-p)
			PASSWORD="$2";shift;
			shift;;

		-l)
			LIBRARY="$2";shift;
			shift;;

		-n)
			OBJNAME="$2";shift;
			shift;;

		-t)
			OBJTYPE="$2";shift;
			shift;;

		-h)
			usage;exit 0;shift;
			shift;;

		--)
			shift; break;;
	esac
done

# Translate options to tuple assignments
if [ "${SERVER}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @server -trim \${ ${SERVER} }$ "
else
	echo "Option -s SERVER is a required option but is not present."
	usage
	exit 2
fi
if [ "${USER}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @user -trim \${ ${USER} }$ "
else
	echo "Option -u USER is a required option but is not present."
	usage
	exit 2
fi
if [ "${PASSWORD}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @password -trim \${ ${PASSWORD} }$ "
else
	echo "Option -p PASSWORD is a required option but is not present."
	usage
	exit 2
fi
if [ "${LIBRARY}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @library -trim \${ ${LIBRARY} }$ "
else
	echo "Option -l LIBRARY is a required option but is not present."
	usage
	exit 2
fi
if [ "${OBJNAME}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @objname -trim \${ ${OBJNAME} }$ "
else
	echo "Option -n OBJNAME is a required option but is not present."
	usage
	exit 2
fi
if [ "${OBJTYPE}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @objtype -trim \${ ${OBJTYPE} }$ "
else
	echo "Option -t OBJTYPE is a required option but is not present."
	usage
	exit 2
fi

# Invocation
java -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}/opt/api-java/examples/listobjs.ublu listObjs \( @server @user @password @library @objname @objtype \) 
exit $?
