/**
 * ublu.smapi implements Ublu support for the IBM z/VM &reg;
 * <a href="https://www.ibm.com/support/knowledgecenter/SSB27U_6.3.0/com.ibm.zvm.v630.hcpa0/hcpa087.htm">System
 * Management Application Programming Interface</a>. Ublu
 * <code>FUNC</code> wrappers for the support are found in examples/pigiron. The
 * {@link ublu.smapi.Host} class is hand-coded, but
 * {@link ublu.smapi.SmapiHelper} is autogenerated and should not be modified.
 * See <a href="http://pigiron.sourceforge.net"> the PigIron Project</a>.
 */
package ublu.smapi;
